# Generated by Django 2.2.2 on 2023-02-11 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evChargerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumerhistory',
            old_name='user',
            new_name='consumer',
        ),
        migrations.RemoveField(
            model_name='dailypropertyreading',
            name='socketliveData',
        ),
        migrations.AddField(
            model_name='consumerhistory',
            name='deviceId',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='consumerhistory',
            name='location',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='dailypropertyreading',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evChargerApp.Device'),
        ),
        migrations.AddField(
            model_name='socketlivedata',
            name='url_field',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sockets',
            name='pending_Command',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sockets',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sockets',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consumerhistory',
            name='property',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
