# Generated by Django 2.2.2 on 2023-03-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evChargerApp', '0002_auto_20230211_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='socketlivedata',
            name='total_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
