# Generated by Django 2.2.2 on 2023-03-15 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evChargerApp', '0003_socketlivedata_total_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socketlivedata',
            name='total_time',
        ),
    ]
