# Generated by Django 2.2.2 on 2023-03-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evChargerApp', '0004_remove_socketlivedata_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='socketlivedata',
            name='total_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
