# Generated by Django 2.2.2 on 2023-03-18 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evChargerApp', '0005_socketlivedata_total_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socketlivedata',
            name='reading_from',
        ),
        migrations.RemoveField(
            model_name='socketlivedata',
            name='reading_to',
        ),
    ]
