# Generated by Django 2.2.2 on 2023-03-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evChargerApp', '0006_auto_20230318_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='socketlivedata',
            name='socket_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
