# Generated by Django 2.2.2 on 2023-04-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evChargerApp', '0009_sensordatadetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorDataDetails',
        ),
    ]
