# Generated by Django 2.2.2 on 2023-04-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evChargerApp', '0012_auto_20230414_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordatadetails',
            name='from_time',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='sensordatadetails',
            name='to_time',
            field=models.DateTimeField(),
        ),
    ]
