# Generated by Django 2.2.2 on 2023-04-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evChargerApp', '0013_auto_20230414_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordatadetails',
            name='from_time',
            field=models.DateTimeField(),
        ),
    ]
