# Generated by Django 2.2.2 on 2023-04-14 06:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('evChargerApp', '0017_auto_20230414_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordatadetails',
            name='from_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 6, 57, 37, 85946, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sensordatadetails',
            name='to_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 6, 57, 37, 86123, tzinfo=utc)),
        ),
    ]
