# Generated by Django 2.2.2 on 2023-04-17 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evChargerApp', '0020_auto_20230417_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor_d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=10)),
                ('status', models.BooleanField()),
                ('on_time', models.DateTimeField()),
                ('off_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
        migrations.AlterField(
            model_name='sensordatadetails',
            name='from_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 12, 12, 16, 37264)),
        ),
        migrations.AlterField(
            model_name='sensordatadetails',
            name='to_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 12, 12, 16, 37428)),
        ),
    ]
