# Generated by Django 2.2.2 on 2023-06-08 14:47

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evChargerApp', '0023_auto_20230608_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensordatadetails',
            name='from_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 14, 47, 21, 367330)),
        ),
        migrations.AlterField(
            model_name='sensordatadetails',
            name='to_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 14, 47, 21, 367521)),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
